### PR TITLE
fix plot's aspect ratio to fit all labels

### PR DESCRIPTION
**Pull request by monodera**

### CODE REVIEW

**Comment by monodera** [comment]
@wanqqq31 I found that the completion rate plots cannot show labels when more than ~5 priorities are in the target list. I made a quick fix (you can see the screenshot in the "File changed" section). Do you mind if this change is merged? I think you have some thoughts when you made the original plots.

**Comment by wanqqq31** [comment]
Screenshot from 2024-07-02 12-52-06

Thanks for the revision. I personally do not like to extend the height of plots that much.. I made some revisions to separate the legend into two columns. Now I think all P0-9 label can be seen. But please let me know you have any concerns.

**Comment by monodera** [comment]
Thanks! I didn't know about these options for the legend configuration. I further made micro-adjustments.

- legend_columns is 1 if the number of priorities is less than 6.
- put a small space between the plot and legend to avoid overlapping with axis labels.

The screenshot in the document is also updated.

**Comment by monodera** [comment]
Screenshot 2024-07-01 at 18 49 20
ppp_result_full

**Comment by wanqqq31** [comment]
Thanks! It looks good.

**Pull request merged**
