### PR TITLE
update manual and demo

### PR DESCRIPTION
**Pull request by wanqqq31**
update demo, the ppp page and home page (flow charts) of manual

### CODE REVIEW

**Comment by monodera** [comment]
Thanks a lot for the comprehensive update. I'm wondering if the order of sections in the Home page is better with ToC->Demo->Workflow. What do you think?

**Comment by monodera** [comment]
I also added optional fields for the ppc list (move ppc_pa to optional, add ppc_code and ppc_priority).

**Comment by wanqqq31** [comment]
Thanks for the checking and modification! 

> I'm wondering if the order of sections in the Home page is better with ToC->Demo->Workflow. 
I do not have any preference. ToC might be better to be on the top of page? Users can easily find the page. Workflow might be better to be put before demo, otherwise I am worried some users might get confused about different observation types only from demo.

**Comment by monodera** [comment]
Yes, I was thinking the same thing. Probably, the demo and flowcharts are important at the first visit, but after that, users would prefer to see the ToC without scrolling the page. I'll make the change.

**Pull request merged**
