### PR TITLE
Configurable exposure time for individual exposure

### PR DESCRIPTION
**Pull request by monodera**
Add a checkbox to indicate simulating a classical proposal and integer input form to specify exposure time per visit. It is in the range between 10s to 7200s with the default to 900s.

The number is propagated down to the uploaded files as a meta data.

Documentation update for PPP with a custom single exptime
- Add description on the optional configuration for the individual exptime.
- Add a list of some constant parameters used in the simulation for transparency to the community.

### CODE REVIEW

**Comment by monodera** [comment]
@wanqqq31 Could you please look at the changes I made to enable to use a custom exposure time per visit.

In particular, the following points need to be reviewed by you.
- Weight depends on the number of required exposures. I scale it with it and I'm wondering if any side effects are present or not.
- In documentation, I list some of constant parameters for clarification (maybe for our team members etc.). If you want to add something, please let me know.

I also changed the way to launch the app. If you want to launch it locally, please use the command as follows.
```
pfs-uploader-cli start-app uploader --port 5008 --prefix="uploader" --autoreload --static-dirs doc="./docs/site/" --static-dirs data="./data" --allow-websocket-origin="localhost:5008"

# http://localhost:5008/uploader/

pfs-uploader-cli start-app admin --port 5009 --prefix="uploader-admin" --autoreload --static-dirs doc="./docs/site/" --static-dirs data="./data" --allow-websocket-origin="localhost:5009"

http://localhost:5009/uploader-admin/
```
```

**Comment by monodera** [comment]
I've added some unrelated fixes. It's not a good practice, though.

**Comment by wanqqq31** [comment]
Thanks for the revisions. I think the parts related to ppp look ok. I did a quick test with example file, it works. One concern is that ppp part of uploader actually does not consider any optimization. For the classical mode,  I suspect users define pointings by themselves, and observatory add calibrators/fillers according to their requirements. Should we ask them to run ppp simulation here..?

**Comment by monodera** [comment]
Exact policy must be discussed in the obsproc team, but I suppose that the online PPP will give a reasonable estimate of Nppc and ROT (or COT). Anyway, adding this flexibility would be needed at some point and disabling this wouldn't cost much. I'll merge it to the dev-main branch.

**Pull request merged**
